// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionConfig } from "./ConnectionConfig";
import type { ConnectionId } from "./ConnectionId";

/**
 * A public snapshot of a connection.
 */
export type ConnectionInfo = { id: ConnectionId, name: string, config: ConnectionConfig, };
