// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId";
import type { TransportConfig } from "./TransportConfig";

/**
 * User-facing definition of a managed connection.
 */
export type ConnectionConfig = { 
/**
 * `None` => the server assigns an id on create.
 */
id?: ConnectionId | null, name: string, transport: TransportConfig, };
