// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parity } from "./Parity";

/**
 * How a connection reaches its device(s). A connection is one transport;
 * the slave id is chosen per request, so one transport can address many
 * devices (TCP gateway or RS-485 bus).
 */
export type TransportConfig = { "type": "tcp", host: string, port: number, } | { "type": "rtu_over_tcp", host: string, port: number, } | { "type": "rtu_over_serial", path: string, baud_rate: number, data_bits: number, parity: Parity, stop_bits: number, };
