// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Modbus slave (unit) identifier. `0` is broadcast for writes.
 */
export type SlaveId = number;
