// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId";

export type CloseRequest = { connection: ConnectionId, };
