// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Opaque identifier for a managed connection (which represents one
 * transport — a TCP socket or a serial port — that may address many slaves).
 */
export type ConnectionId = string;
