// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConnectionId } from "./ConnectionId";
import type { Quantity } from "./Quantity";
import type { RegisterAddress } from "./RegisterAddress";
import type { SlaveId } from "./SlaveId";

export type ReadHoldingRegistersRequest = { connection: ConnectionId, slave: SlaveId, address: RegisterAddress, quantity: Quantity, };
